// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.1
// source: badezimmer.proto

package badezimmer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceKind int32

const (
	DeviceKind_UNKNOWN_KIND  DeviceKind = 0
	DeviceKind_SENSOR_KIND   DeviceKind = 1
	DeviceKind_ACTUATOR_KIND DeviceKind = 2
)

// Enum value maps for DeviceKind.
var (
	DeviceKind_name = map[int32]string{
		0: "UNKNOWN_KIND",
		1: "SENSOR_KIND",
		2: "ACTUATOR_KIND",
	}
	DeviceKind_value = map[string]int32{
		"UNKNOWN_KIND":  0,
		"SENSOR_KIND":   1,
		"ACTUATOR_KIND": 2,
	}
)

func (x DeviceKind) Enum() *DeviceKind {
	p := new(DeviceKind)
	*p = x
	return p
}

func (x DeviceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_badezimmer_proto_enumTypes[0].Descriptor()
}

func (DeviceKind) Type() protoreflect.EnumType {
	return &file_badezimmer_proto_enumTypes[0]
}

func (x DeviceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceKind.Descriptor instead.
func (DeviceKind) EnumDescriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{0}
}

type DeviceStatus int32

const (
	DeviceStatus_UNKNOWN_DEVICE_STATUS DeviceStatus = 0
	DeviceStatus_OFFLINE_DEVICE_STATUS DeviceStatus = 1
	DeviceStatus_ONLINE_DEVICE_STATUS  DeviceStatus = 2
	DeviceStatus_ERROR_DEVICE_STATUS   DeviceStatus = 3
)

// Enum value maps for DeviceStatus.
var (
	DeviceStatus_name = map[int32]string{
		0: "UNKNOWN_DEVICE_STATUS",
		1: "OFFLINE_DEVICE_STATUS",
		2: "ONLINE_DEVICE_STATUS",
		3: "ERROR_DEVICE_STATUS",
	}
	DeviceStatus_value = map[string]int32{
		"UNKNOWN_DEVICE_STATUS": 0,
		"OFFLINE_DEVICE_STATUS": 1,
		"ONLINE_DEVICE_STATUS":  2,
		"ERROR_DEVICE_STATUS":   3,
	}
)

func (x DeviceStatus) Enum() *DeviceStatus {
	p := new(DeviceStatus)
	*p = x
	return p
}

func (x DeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_badezimmer_proto_enumTypes[1].Descriptor()
}

func (DeviceStatus) Type() protoreflect.EnumType {
	return &file_badezimmer_proto_enumTypes[1]
}

func (x DeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStatus.Descriptor instead.
func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{1}
}

type DeviceCategory int32

const (
	DeviceCategory_UNKNOWN_CATEGORY DeviceCategory = 0
	DeviceCategory_LIGHT_LAMP       DeviceCategory = 1
	DeviceCategory_FART_DETECTOR    DeviceCategory = 2
	DeviceCategory_TOILET           DeviceCategory = 3
	DeviceCategory_SINK             DeviceCategory = 4
	DeviceCategory_WATER_LEAK       DeviceCategory = 5
)

// Enum value maps for DeviceCategory.
var (
	DeviceCategory_name = map[int32]string{
		0: "UNKNOWN_CATEGORY",
		1: "LIGHT_LAMP",
		2: "FART_DETECTOR",
		3: "TOILET",
		4: "SINK",
		5: "WATER_LEAK",
	}
	DeviceCategory_value = map[string]int32{
		"UNKNOWN_CATEGORY": 0,
		"LIGHT_LAMP":       1,
		"FART_DETECTOR":    2,
		"TOILET":           3,
		"SINK":             4,
		"WATER_LEAK":       5,
	}
)

func (x DeviceCategory) Enum() *DeviceCategory {
	p := new(DeviceCategory)
	*p = x
	return p
}

func (x DeviceCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_badezimmer_proto_enumTypes[2].Descriptor()
}

func (DeviceCategory) Type() protoreflect.EnumType {
	return &file_badezimmer_proto_enumTypes[2]
}

func (x DeviceCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceCategory.Descriptor instead.
func (DeviceCategory) EnumDescriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{2}
}

type TransportProtocol int32

const (
	TransportProtocol_UNKNOWN_PROTOCOL TransportProtocol = 0
	TransportProtocol_TCP_PROTOCOL     TransportProtocol = 1
	TransportProtocol_UDP_PROTOCOL     TransportProtocol = 2
)

// Enum value maps for TransportProtocol.
var (
	TransportProtocol_name = map[int32]string{
		0: "UNKNOWN_PROTOCOL",
		1: "TCP_PROTOCOL",
		2: "UDP_PROTOCOL",
	}
	TransportProtocol_value = map[string]int32{
		"UNKNOWN_PROTOCOL": 0,
		"TCP_PROTOCOL":     1,
		"UDP_PROTOCOL":     2,
	}
)

func (x TransportProtocol) Enum() *TransportProtocol {
	p := new(TransportProtocol)
	*p = x
	return p
}

func (x TransportProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_badezimmer_proto_enumTypes[3].Descriptor()
}

func (TransportProtocol) Type() protoreflect.EnumType {
	return &file_badezimmer_proto_enumTypes[3]
}

func (x TransportProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportProtocol.Descriptor instead.
func (TransportProtocol) EnumDescriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{3}
}

type ErrorCode int32

const (
	ErrorCode_UNKNOWN_ERROR    ErrorCode = 0
	ErrorCode_DEVICE_NOT_FOUND ErrorCode = 1
	ErrorCode_INVALID_COMMAND  ErrorCode = 2
	ErrorCode_DEVICE_OFFLINE   ErrorCode = 3
	ErrorCode_VALIDATION_ERROR ErrorCode = 4
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "DEVICE_NOT_FOUND",
		2: "INVALID_COMMAND",
		3: "DEVICE_OFFLINE",
		4: "VALIDATION_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN_ERROR":    0,
		"DEVICE_NOT_FOUND": 1,
		"INVALID_COMMAND":  2,
		"DEVICE_OFFLINE":   3,
		"VALIDATION_ERROR": 4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_badezimmer_proto_enumTypes[4].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_badezimmer_proto_enumTypes[4]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{4}
}

type MDNSType int32

const (
	MDNSType_MDNS_A   MDNSType = 0
	MDNSType_MDNS_PTR MDNSType = 1
	MDNSType_MDNS_SRV MDNSType = 2
	MDNSType_MDNS_TXT MDNSType = 3
)

// Enum value maps for MDNSType.
var (
	MDNSType_name = map[int32]string{
		0: "MDNS_A",
		1: "MDNS_PTR",
		2: "MDNS_SRV",
		3: "MDNS_TXT",
	}
	MDNSType_value = map[string]int32{
		"MDNS_A":   0,
		"MDNS_PTR": 1,
		"MDNS_SRV": 2,
		"MDNS_TXT": 3,
	}
)

func (x MDNSType) Enum() *MDNSType {
	p := new(MDNSType)
	*p = x
	return p
}

func (x MDNSType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MDNSType) Descriptor() protoreflect.EnumDescriptor {
	return file_badezimmer_proto_enumTypes[5].Descriptor()
}

func (MDNSType) Type() protoreflect.EnumType {
	return &file_badezimmer_proto_enumTypes[5]
}

func (x MDNSType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MDNSType.Descriptor instead.
func (MDNSType) EnumDescriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{5}
}

type ConnectedDevice struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceName        string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Kind              DeviceKind             `protobuf:"varint,3,opt,name=kind,proto3,enum=badezimmer.DeviceKind" json:"kind,omitempty"`
	Status            DeviceStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=badezimmer.DeviceStatus" json:"status,omitempty"`
	Ips               []string               `protobuf:"bytes,5,rep,name=ips,proto3" json:"ips,omitempty"`
	Port              int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Properties        map[string]string      `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Category          DeviceCategory         `protobuf:"varint,8,opt,name=category,proto3,enum=badezimmer.DeviceCategory" json:"category,omitempty"`
	TransportProtocol TransportProtocol      `protobuf:"varint,9,opt,name=transport_protocol,json=transportProtocol,proto3,enum=badezimmer.TransportProtocol" json:"transport_protocol,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectedDevice) Reset() {
	*x = ConnectedDevice{}
	mi := &file_badezimmer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedDevice) ProtoMessage() {}

func (x *ConnectedDevice) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedDevice.ProtoReflect.Descriptor instead.
func (*ConnectedDevice) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectedDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectedDevice) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *ConnectedDevice) GetKind() DeviceKind {
	if x != nil {
		return x.Kind
	}
	return DeviceKind_UNKNOWN_KIND
}

func (x *ConnectedDevice) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_UNKNOWN_DEVICE_STATUS
}

func (x *ConnectedDevice) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *ConnectedDevice) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectedDevice) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ConnectedDevice) GetCategory() DeviceCategory {
	if x != nil {
		return x.Category
	}
	return DeviceCategory_UNKNOWN_CATEGORY
}

func (x *ConnectedDevice) GetTransportProtocol() TransportProtocol {
	if x != nil {
		return x.TransportProtocol
	}
	return TransportProtocol_UNKNOWN_PROTOCOL
}

type ListConnectedDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterKind    *DeviceKind            `protobuf:"varint,1,opt,name=filter_kind,json=filterKind,proto3,enum=badezimmer.DeviceKind,oneof" json:"filter_kind,omitempty"`
	FilterName    *string                `protobuf:"bytes,2,opt,name=filter_name,json=filterName,proto3,oneof" json:"filter_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectedDevicesRequest) Reset() {
	*x = ListConnectedDevicesRequest{}
	mi := &file_badezimmer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectedDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectedDevicesRequest) ProtoMessage() {}

func (x *ListConnectedDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectedDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListConnectedDevicesRequest) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{1}
}

func (x *ListConnectedDevicesRequest) GetFilterKind() DeviceKind {
	if x != nil && x.FilterKind != nil {
		return *x.FilterKind
	}
	return DeviceKind_UNKNOWN_KIND
}

func (x *ListConnectedDevicesRequest) GetFilterName() string {
	if x != nil && x.FilterName != nil {
		return *x.FilterName
	}
	return ""
}

type ListConnectedDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*ConnectedDevice     `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectedDevicesResponse) Reset() {
	*x = ListConnectedDevicesResponse{}
	mi := &file_badezimmer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectedDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectedDevicesResponse) ProtoMessage() {}

func (x *ListConnectedDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectedDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListConnectedDevicesResponse) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{2}
}

func (x *ListConnectedDevicesResponse) GetDevices() []*ConnectedDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type SendActuatorCommandRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*SendActuatorCommandRequest_LightAction
	//	*SendActuatorCommandRequest_SinkAction
	Action        isSendActuatorCommandRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendActuatorCommandRequest) Reset() {
	*x = SendActuatorCommandRequest{}
	mi := &file_badezimmer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActuatorCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActuatorCommandRequest) ProtoMessage() {}

func (x *SendActuatorCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActuatorCommandRequest.ProtoReflect.Descriptor instead.
func (*SendActuatorCommandRequest) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{3}
}

func (x *SendActuatorCommandRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SendActuatorCommandRequest) GetAction() isSendActuatorCommandRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *SendActuatorCommandRequest) GetLightAction() *LightLampActionRequest {
	if x != nil {
		if x, ok := x.Action.(*SendActuatorCommandRequest_LightAction); ok {
			return x.LightAction
		}
	}
	return nil
}

func (x *SendActuatorCommandRequest) GetSinkAction() *SinkActionRequest {
	if x != nil {
		if x, ok := x.Action.(*SendActuatorCommandRequest_SinkAction); ok {
			return x.SinkAction
		}
	}
	return nil
}

type isSendActuatorCommandRequest_Action interface {
	isSendActuatorCommandRequest_Action()
}

type SendActuatorCommandRequest_LightAction struct {
	LightAction *LightLampActionRequest `protobuf:"bytes,2,opt,name=light_action,json=lightAction,proto3,oneof"`
}

type SendActuatorCommandRequest_SinkAction struct {
	SinkAction *SinkActionRequest `protobuf:"bytes,3,opt,name=sink_action,json=sinkAction,proto3,oneof"`
}

func (*SendActuatorCommandRequest_LightAction) isSendActuatorCommandRequest_Action() {}

func (*SendActuatorCommandRequest_SinkAction) isSendActuatorCommandRequest_Action() {}

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=badezimmer.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_badezimmer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorDetails) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_UNKNOWN_ERROR
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BadezimmerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*BadezimmerRequest_Empty
	//	*BadezimmerRequest_ListDevices
	//	*BadezimmerRequest_SendActuatorCommand
	Request       isBadezimmerRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadezimmerRequest) Reset() {
	*x = BadezimmerRequest{}
	mi := &file_badezimmer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadezimmerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadezimmerRequest) ProtoMessage() {}

func (x *BadezimmerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadezimmerRequest.ProtoReflect.Descriptor instead.
func (*BadezimmerRequest) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{5}
}

func (x *BadezimmerRequest) GetRequest() isBadezimmerRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *BadezimmerRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Request.(*BadezimmerRequest_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *BadezimmerRequest) GetListDevices() *ListConnectedDevicesRequest {
	if x != nil {
		if x, ok := x.Request.(*BadezimmerRequest_ListDevices); ok {
			return x.ListDevices
		}
	}
	return nil
}

func (x *BadezimmerRequest) GetSendActuatorCommand() *SendActuatorCommandRequest {
	if x != nil {
		if x, ok := x.Request.(*BadezimmerRequest_SendActuatorCommand); ok {
			return x.SendActuatorCommand
		}
	}
	return nil
}

type isBadezimmerRequest_Request interface {
	isBadezimmerRequest_Request()
}

type BadezimmerRequest_Empty struct {
	Empty *emptypb.Empty `protobuf:"bytes,1,opt,name=empty,proto3,oneof"`
}

type BadezimmerRequest_ListDevices struct {
	ListDevices *ListConnectedDevicesRequest `protobuf:"bytes,2,opt,name=list_devices,json=listDevices,proto3,oneof"`
}

type BadezimmerRequest_SendActuatorCommand struct {
	SendActuatorCommand *SendActuatorCommandRequest `protobuf:"bytes,3,opt,name=send_actuator_command,json=sendActuatorCommand,proto3,oneof"`
}

func (*BadezimmerRequest_Empty) isBadezimmerRequest_Request() {}

func (*BadezimmerRequest_ListDevices) isBadezimmerRequest_Request() {}

func (*BadezimmerRequest_SendActuatorCommand) isBadezimmerRequest_Request() {}

type BadezimmerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*BadezimmerResponse_Empty
	//	*BadezimmerResponse_Error
	//	*BadezimmerResponse_ListDevicesResponse
	//	*BadezimmerResponse_SendActuatorCommandResponse
	Response      isBadezimmerResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadezimmerResponse) Reset() {
	*x = BadezimmerResponse{}
	mi := &file_badezimmer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadezimmerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadezimmerResponse) ProtoMessage() {}

func (x *BadezimmerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadezimmerResponse.ProtoReflect.Descriptor instead.
func (*BadezimmerResponse) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{6}
}

func (x *BadezimmerResponse) GetResponse() isBadezimmerResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *BadezimmerResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Response.(*BadezimmerResponse_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *BadezimmerResponse) GetError() *ErrorDetails {
	if x != nil {
		if x, ok := x.Response.(*BadezimmerResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *BadezimmerResponse) GetListDevicesResponse() *ListConnectedDevicesResponse {
	if x != nil {
		if x, ok := x.Response.(*BadezimmerResponse_ListDevicesResponse); ok {
			return x.ListDevicesResponse
		}
	}
	return nil
}

func (x *BadezimmerResponse) GetSendActuatorCommandResponse() *SendActuatorCommandResponse {
	if x != nil {
		if x, ok := x.Response.(*BadezimmerResponse_SendActuatorCommandResponse); ok {
			return x.SendActuatorCommandResponse
		}
	}
	return nil
}

type isBadezimmerResponse_Response interface {
	isBadezimmerResponse_Response()
}

type BadezimmerResponse_Empty struct {
	Empty *emptypb.Empty `protobuf:"bytes,1,opt,name=empty,proto3,oneof"`
}

type BadezimmerResponse_Error struct {
	Error *ErrorDetails `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type BadezimmerResponse_ListDevicesResponse struct {
	ListDevicesResponse *ListConnectedDevicesResponse `protobuf:"bytes,3,opt,name=list_devices_response,json=listDevicesResponse,proto3,oneof"`
}

type BadezimmerResponse_SendActuatorCommandResponse struct {
	SendActuatorCommandResponse *SendActuatorCommandResponse `protobuf:"bytes,4,opt,name=send_actuator_command_response,json=sendActuatorCommandResponse,proto3,oneof"`
}

func (*BadezimmerResponse_Empty) isBadezimmerResponse_Response() {}

func (*BadezimmerResponse_Error) isBadezimmerResponse_Response() {}

func (*BadezimmerResponse_ListDevicesResponse) isBadezimmerResponse_Response() {}

func (*BadezimmerResponse_SendActuatorCommandResponse) isBadezimmerResponse_Response() {}

type SendActuatorCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendActuatorCommandResponse) Reset() {
	*x = SendActuatorCommandResponse{}
	mi := &file_badezimmer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActuatorCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActuatorCommandResponse) ProtoMessage() {}

func (x *SendActuatorCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActuatorCommandResponse.ProtoReflect.Descriptor instead.
func (*SendActuatorCommandResponse) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{7}
}

func (x *SendActuatorCommandResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint32                 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"` // Represents the color as an unsigned 32-bit integer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_badezimmer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{8}
}

func (x *Color) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type LightLampActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TurnOn        *bool                  `protobuf:"varint,1,opt,name=turn_on,json=turnOn,proto3,oneof" json:"turn_on,omitempty"`
	Brightness    *int32                 `protobuf:"varint,2,opt,name=brightness,proto3,oneof" json:"brightness,omitempty"`
	Color         *Color                 `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightLampActionRequest) Reset() {
	*x = LightLampActionRequest{}
	mi := &file_badezimmer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightLampActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightLampActionRequest) ProtoMessage() {}

func (x *LightLampActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightLampActionRequest.ProtoReflect.Descriptor instead.
func (*LightLampActionRequest) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{9}
}

func (x *LightLampActionRequest) GetTurnOn() bool {
	if x != nil && x.TurnOn != nil {
		return *x.TurnOn
	}
	return false
}

func (x *LightLampActionRequest) GetBrightness() int32 {
	if x != nil && x.Brightness != nil {
		return *x.Brightness
	}
	return 0
}

func (x *LightLampActionRequest) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type SinkActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TurnOn        *bool                  `protobuf:"varint,1,opt,name=turn_on,json=turnOn,proto3,oneof" json:"turn_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinkActionRequest) Reset() {
	*x = SinkActionRequest{}
	mi := &file_badezimmer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinkActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkActionRequest) ProtoMessage() {}

func (x *SinkActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkActionRequest.ProtoReflect.Descriptor instead.
func (*SinkActionRequest) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{10}
}

func (x *SinkActionRequest) GetTurnOn() bool {
	if x != nil && x.TurnOn != nil {
		return *x.TurnOn
	}
	return false
}

type MDNSQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          MDNSType               `protobuf:"varint,2,opt,name=type,proto3,enum=badezimmer.MDNSType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDNSQuestion) Reset() {
	*x = MDNSQuestion{}
	mi := &file_badezimmer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDNSQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDNSQuestion) ProtoMessage() {}

func (x *MDNSQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDNSQuestion.ProtoReflect.Descriptor instead.
func (*MDNSQuestion) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{11}
}

func (x *MDNSQuestion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MDNSQuestion) GetType() MDNSType {
	if x != nil {
		return x.Type
	}
	return MDNSType_MDNS_A
}

type MDNSQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*MDNSQuestion        `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDNSQueryRequest) Reset() {
	*x = MDNSQueryRequest{}
	mi := &file_badezimmer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDNSQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDNSQueryRequest) ProtoMessage() {}

func (x *MDNSQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDNSQueryRequest.ProtoReflect.Descriptor instead.
func (*MDNSQueryRequest) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{12}
}

func (x *MDNSQueryRequest) GetQuestions() []*MDNSQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

type MDNSPointerRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DomainName    string                 `protobuf:"bytes,2,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDNSPointerRecord) Reset() {
	*x = MDNSPointerRecord{}
	mi := &file_badezimmer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDNSPointerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDNSPointerRecord) ProtoMessage() {}

func (x *MDNSPointerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDNSPointerRecord.ProtoReflect.Descriptor instead.
func (*MDNSPointerRecord) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{13}
}

func (x *MDNSPointerRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MDNSPointerRecord) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

type MDNSSRVRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Protocol      TransportProtocol      `protobuf:"varint,4,opt,name=protocol,proto3,enum=badezimmer.TransportProtocol" json:"protocol,omitempty"`
	Service       string                 `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	Instance      string                 `protobuf:"bytes,6,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDNSSRVRecord) Reset() {
	*x = MDNSSRVRecord{}
	mi := &file_badezimmer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDNSSRVRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDNSSRVRecord) ProtoMessage() {}

func (x *MDNSSRVRecord) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDNSSRVRecord.ProtoReflect.Descriptor instead.
func (*MDNSSRVRecord) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{14}
}

func (x *MDNSSRVRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MDNSSRVRecord) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MDNSSRVRecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MDNSSRVRecord) GetProtocol() TransportProtocol {
	if x != nil {
		return x.Protocol
	}
	return TransportProtocol_UNKNOWN_PROTOCOL
}

func (x *MDNSSRVRecord) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *MDNSSRVRecord) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type MDNSTextRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Entries       map[string]string      `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDNSTextRecord) Reset() {
	*x = MDNSTextRecord{}
	mi := &file_badezimmer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDNSTextRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDNSTextRecord) ProtoMessage() {}

func (x *MDNSTextRecord) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDNSTextRecord.ProtoReflect.Descriptor instead.
func (*MDNSTextRecord) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{15}
}

func (x *MDNSTextRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MDNSTextRecord) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MDNSARecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDNSARecord) Reset() {
	*x = MDNSARecord{}
	mi := &file_badezimmer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDNSARecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDNSARecord) ProtoMessage() {}

func (x *MDNSARecord) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDNSARecord.ProtoReflect.Descriptor instead.
func (*MDNSARecord) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{16}
}

func (x *MDNSARecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MDNSARecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type MDNSRecord struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ttl        int32                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	CacheFlush bool                   `protobuf:"varint,3,opt,name=cache_flush,json=cacheFlush,proto3" json:"cache_flush,omitempty"`
	// Types that are valid to be assigned to Record:
	//
	//	*MDNSRecord_PtrRecord
	//	*MDNSRecord_SrvRecord
	//	*MDNSRecord_TxtRecord
	//	*MDNSRecord_ARecord
	Record        isMDNSRecord_Record `protobuf_oneof:"record"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDNSRecord) Reset() {
	*x = MDNSRecord{}
	mi := &file_badezimmer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDNSRecord) ProtoMessage() {}

func (x *MDNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDNSRecord.ProtoReflect.Descriptor instead.
func (*MDNSRecord) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{17}
}

func (x *MDNSRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MDNSRecord) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *MDNSRecord) GetCacheFlush() bool {
	if x != nil {
		return x.CacheFlush
	}
	return false
}

func (x *MDNSRecord) GetRecord() isMDNSRecord_Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *MDNSRecord) GetPtrRecord() *MDNSPointerRecord {
	if x != nil {
		if x, ok := x.Record.(*MDNSRecord_PtrRecord); ok {
			return x.PtrRecord
		}
	}
	return nil
}

func (x *MDNSRecord) GetSrvRecord() *MDNSSRVRecord {
	if x != nil {
		if x, ok := x.Record.(*MDNSRecord_SrvRecord); ok {
			return x.SrvRecord
		}
	}
	return nil
}

func (x *MDNSRecord) GetTxtRecord() *MDNSTextRecord {
	if x != nil {
		if x, ok := x.Record.(*MDNSRecord_TxtRecord); ok {
			return x.TxtRecord
		}
	}
	return nil
}

func (x *MDNSRecord) GetARecord() *MDNSARecord {
	if x != nil {
		if x, ok := x.Record.(*MDNSRecord_ARecord); ok {
			return x.ARecord
		}
	}
	return nil
}

type isMDNSRecord_Record interface {
	isMDNSRecord_Record()
}

type MDNSRecord_PtrRecord struct {
	PtrRecord *MDNSPointerRecord `protobuf:"bytes,4,opt,name=ptr_record,json=ptrRecord,proto3,oneof"`
}

type MDNSRecord_SrvRecord struct {
	SrvRecord *MDNSSRVRecord `protobuf:"bytes,5,opt,name=srv_record,json=srvRecord,proto3,oneof"`
}

type MDNSRecord_TxtRecord struct {
	TxtRecord *MDNSTextRecord `protobuf:"bytes,6,opt,name=txt_record,json=txtRecord,proto3,oneof"`
}

type MDNSRecord_ARecord struct {
	ARecord *MDNSARecord `protobuf:"bytes,7,opt,name=a_record,json=aRecord,proto3,oneof"`
}

func (*MDNSRecord_PtrRecord) isMDNSRecord_Record() {}

func (*MDNSRecord_SrvRecord) isMDNSRecord_Record() {}

func (*MDNSRecord_TxtRecord) isMDNSRecord_Record() {}

func (*MDNSRecord_ARecord) isMDNSRecord_Record() {}

type MDNSQueryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Answers           []*MDNSRecord          `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	AdditionalRecords []*MDNSRecord          `protobuf:"bytes,2,rep,name=additional_records,json=additionalRecords,proto3" json:"additional_records,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MDNSQueryResponse) Reset() {
	*x = MDNSQueryResponse{}
	mi := &file_badezimmer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDNSQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDNSQueryResponse) ProtoMessage() {}

func (x *MDNSQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDNSQueryResponse.ProtoReflect.Descriptor instead.
func (*MDNSQueryResponse) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{18}
}

func (x *MDNSQueryResponse) GetAnswers() []*MDNSRecord {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *MDNSQueryResponse) GetAdditionalRecords() []*MDNSRecord {
	if x != nil {
		return x.AdditionalRecords
	}
	return nil
}

type MDNS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId uint32                 `protobuf:"fixed32,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*MDNS_QueryRequest
	//	*MDNS_QueryResponse
	Data          isMDNS_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDNS) Reset() {
	*x = MDNS{}
	mi := &file_badezimmer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDNS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDNS) ProtoMessage() {}

func (x *MDNS) ProtoReflect() protoreflect.Message {
	mi := &file_badezimmer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDNS.ProtoReflect.Descriptor instead.
func (*MDNS) Descriptor() ([]byte, []int) {
	return file_badezimmer_proto_rawDescGZIP(), []int{19}
}

func (x *MDNS) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *MDNS) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MDNS) GetData() isMDNS_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MDNS) GetQueryRequest() *MDNSQueryRequest {
	if x != nil {
		if x, ok := x.Data.(*MDNS_QueryRequest); ok {
			return x.QueryRequest
		}
	}
	return nil
}

func (x *MDNS) GetQueryResponse() *MDNSQueryResponse {
	if x != nil {
		if x, ok := x.Data.(*MDNS_QueryResponse); ok {
			return x.QueryResponse
		}
	}
	return nil
}

type isMDNS_Data interface {
	isMDNS_Data()
}

type MDNS_QueryRequest struct {
	QueryRequest *MDNSQueryRequest `protobuf:"bytes,3,opt,name=query_request,json=queryRequest,proto3,oneof"`
}

type MDNS_QueryResponse struct {
	QueryResponse *MDNSQueryResponse `protobuf:"bytes,4,opt,name=query_response,json=queryResponse,proto3,oneof"`
}

func (*MDNS_QueryRequest) isMDNS_Data() {}

func (*MDNS_QueryResponse) isMDNS_Data() {}

var File_badezimmer_proto protoreflect.FileDescriptor

const file_badezimmer_proto_rawDesc = "" +
	"\n" +
	"\x10badezimmer.proto\x12\n" +
	"badezimmer\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd8\x03\n" +
	"\x0fConnectedDevice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12*\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x16.badezimmer.DeviceKindR\x04kind\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.badezimmer.DeviceStatusR\x06status\x12\x10\n" +
	"\x03ips\x18\x05 \x03(\tR\x03ips\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12K\n" +
	"\n" +
	"properties\x18\a \x03(\v2+.badezimmer.ConnectedDevice.PropertiesEntryR\n" +
	"properties\x126\n" +
	"\bcategory\x18\b \x01(\x0e2\x1a.badezimmer.DeviceCategoryR\bcategory\x12L\n" +
	"\x12transport_protocol\x18\t \x01(\x0e2\x1d.badezimmer.TransportProtocolR\x11transportProtocol\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x1bListConnectedDevicesRequest\x12<\n" +
	"\vfilter_kind\x18\x01 \x01(\x0e2\x16.badezimmer.DeviceKindH\x00R\n" +
	"filterKind\x88\x01\x01\x12$\n" +
	"\vfilter_name\x18\x02 \x01(\tH\x01R\n" +
	"filterName\x88\x01\x01B\x0e\n" +
	"\f_filter_kindB\x0e\n" +
	"\f_filter_name\"U\n" +
	"\x1cListConnectedDevicesResponse\x125\n" +
	"\adevices\x18\x01 \x03(\v2\x1b.badezimmer.ConnectedDeviceR\adevices\"\xce\x01\n" +
	"\x1aSendActuatorCommandRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12G\n" +
	"\flight_action\x18\x02 \x01(\v2\".badezimmer.LightLampActionRequestH\x00R\vlightAction\x12@\n" +
	"\vsink_action\x18\x03 \x01(\v2\x1d.badezimmer.SinkActionRequestH\x00R\n" +
	"sinkActionB\b\n" +
	"\x06action\"\xd4\x01\n" +
	"\fErrorDetails\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.badezimmer.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\bmetadata\x18\x03 \x03(\v2&.badezimmer.ErrorDetails.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x01\n" +
	"\x11BadezimmerRequest\x12.\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05empty\x12L\n" +
	"\flist_devices\x18\x02 \x01(\v2'.badezimmer.ListConnectedDevicesRequestH\x00R\vlistDevices\x12\\\n" +
	"\x15send_actuator_command\x18\x03 \x01(\v2&.badezimmer.SendActuatorCommandRequestH\x00R\x13sendActuatorCommandB\t\n" +
	"\arequest\"\xd2\x02\n" +
	"\x12BadezimmerResponse\x12.\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05empty\x120\n" +
	"\x05error\x18\x02 \x01(\v2\x18.badezimmer.ErrorDetailsH\x00R\x05error\x12^\n" +
	"\x15list_devices_response\x18\x03 \x01(\v2(.badezimmer.ListConnectedDevicesResponseH\x00R\x13listDevicesResponse\x12n\n" +
	"\x1esend_actuator_command_response\x18\x04 \x01(\v2'.badezimmer.SendActuatorCommandResponseH\x00R\x1bsendActuatorCommandResponseB\n" +
	"\n" +
	"\bresponse\"H\n" +
	"\x1bSendActuatorCommandResponse\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\x1d\n" +
	"\x05Color\x12\x14\n" +
	"\x05value\x18\x01 \x01(\aR\x05value\"\xae\x01\n" +
	"\x16LightLampActionRequest\x12\x1c\n" +
	"\aturn_on\x18\x01 \x01(\bH\x00R\x06turnOn\x88\x01\x01\x12#\n" +
	"\n" +
	"brightness\x18\x02 \x01(\x05H\x01R\n" +
	"brightness\x88\x01\x01\x12,\n" +
	"\x05color\x18\x03 \x01(\v2\x11.badezimmer.ColorH\x02R\x05color\x88\x01\x01B\n" +
	"\n" +
	"\b_turn_onB\r\n" +
	"\v_brightnessB\b\n" +
	"\x06_color\"=\n" +
	"\x11SinkActionRequest\x12\x1c\n" +
	"\aturn_on\x18\x01 \x01(\bH\x00R\x06turnOn\x88\x01\x01B\n" +
	"\n" +
	"\b_turn_on\"L\n" +
	"\fMDNSQuestion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.badezimmer.MDNSTypeR\x04type\"J\n" +
	"\x10MDNSQueryRequest\x126\n" +
	"\tquestions\x18\x01 \x03(\v2\x18.badezimmer.MDNSQuestionR\tquestions\"H\n" +
	"\x11MDNSPointerRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vdomain_name\x18\x02 \x01(\tR\n" +
	"domainName\"\xc0\x01\n" +
	"\rMDNSSRVRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x129\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x1d.badezimmer.TransportProtocolR\bprotocol\x12\x18\n" +
	"\aservice\x18\x05 \x01(\tR\aservice\x12\x1a\n" +
	"\binstance\x18\x06 \x01(\tR\binstance\"\xa3\x01\n" +
	"\x0eMDNSTextRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\aentries\x18\x02 \x03(\v2'.badezimmer.MDNSTextRecord.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\vMDNSARecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xcc\x02\n" +
	"\n" +
	"MDNSRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x05R\x03ttl\x12\x1f\n" +
	"\vcache_flush\x18\x03 \x01(\bR\n" +
	"cacheFlush\x12>\n" +
	"\n" +
	"ptr_record\x18\x04 \x01(\v2\x1d.badezimmer.MDNSPointerRecordH\x00R\tptrRecord\x12:\n" +
	"\n" +
	"srv_record\x18\x05 \x01(\v2\x19.badezimmer.MDNSSRVRecordH\x00R\tsrvRecord\x12;\n" +
	"\n" +
	"txt_record\x18\x06 \x01(\v2\x1a.badezimmer.MDNSTextRecordH\x00R\ttxtRecord\x124\n" +
	"\ba_record\x18\a \x01(\v2\x17.badezimmer.MDNSARecordH\x00R\aaRecordB\b\n" +
	"\x06record\"\x8c\x01\n" +
	"\x11MDNSQueryResponse\x120\n" +
	"\aanswers\x18\x01 \x03(\v2\x16.badezimmer.MDNSRecordR\aanswers\x12E\n" +
	"\x12additional_records\x18\x02 \x03(\v2\x16.badezimmer.MDNSRecordR\x11additionalRecords\"\xfc\x01\n" +
	"\x04MDNS\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\aR\rtransactionId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12C\n" +
	"\rquery_request\x18\x03 \x01(\v2\x1c.badezimmer.MDNSQueryRequestH\x00R\fqueryRequest\x12F\n" +
	"\x0equery_response\x18\x04 \x01(\v2\x1d.badezimmer.MDNSQueryResponseH\x00R\rqueryResponseB\x06\n" +
	"\x04data*B\n" +
	"\n" +
	"DeviceKind\x12\x10\n" +
	"\fUNKNOWN_KIND\x10\x00\x12\x0f\n" +
	"\vSENSOR_KIND\x10\x01\x12\x11\n" +
	"\rACTUATOR_KIND\x10\x02*w\n" +
	"\fDeviceStatus\x12\x19\n" +
	"\x15UNKNOWN_DEVICE_STATUS\x10\x00\x12\x19\n" +
	"\x15OFFLINE_DEVICE_STATUS\x10\x01\x12\x18\n" +
	"\x14ONLINE_DEVICE_STATUS\x10\x02\x12\x17\n" +
	"\x13ERROR_DEVICE_STATUS\x10\x03*o\n" +
	"\x0eDeviceCategory\x12\x14\n" +
	"\x10UNKNOWN_CATEGORY\x10\x00\x12\x0e\n" +
	"\n" +
	"LIGHT_LAMP\x10\x01\x12\x11\n" +
	"\rFART_DETECTOR\x10\x02\x12\n" +
	"\n" +
	"\x06TOILET\x10\x03\x12\b\n" +
	"\x04SINK\x10\x04\x12\x0e\n" +
	"\n" +
	"WATER_LEAK\x10\x05*M\n" +
	"\x11TransportProtocol\x12\x14\n" +
	"\x10UNKNOWN_PROTOCOL\x10\x00\x12\x10\n" +
	"\fTCP_PROTOCOL\x10\x01\x12\x10\n" +
	"\fUDP_PROTOCOL\x10\x02*s\n" +
	"\tErrorCode\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x12\x14\n" +
	"\x10DEVICE_NOT_FOUND\x10\x01\x12\x13\n" +
	"\x0fINVALID_COMMAND\x10\x02\x12\x12\n" +
	"\x0eDEVICE_OFFLINE\x10\x03\x12\x14\n" +
	"\x10VALIDATION_ERROR\x10\x04*@\n" +
	"\bMDNSType\x12\n" +
	"\n" +
	"\x06MDNS_A\x10\x00\x12\f\n" +
	"\bMDNS_PTR\x10\x01\x12\f\n" +
	"\bMDNS_SRV\x10\x02\x12\f\n" +
	"\bMDNS_TXT\x10\x032\xea\x01\n" +
	"\x11BadezimmerService\x12k\n" +
	"\x14ListConnectedDevices\x12'.badezimmer.ListConnectedDevicesRequest\x1a(.badezimmer.ListConnectedDevicesResponse\"\x00\x12h\n" +
	"\x13SendActuatorCommand\x12&.badezimmer.SendActuatorCommandRequest\x1a'.badezimmer.SendActuatorCommandResponse\"\x00B1Z/github.com/talDoFlemis/badezimmer-go/badezimmerb\x06proto3"

var (
	file_badezimmer_proto_rawDescOnce sync.Once
	file_badezimmer_proto_rawDescData []byte
)

func file_badezimmer_proto_rawDescGZIP() []byte {
	file_badezimmer_proto_rawDescOnce.Do(func() {
		file_badezimmer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_badezimmer_proto_rawDesc), len(file_badezimmer_proto_rawDesc)))
	})
	return file_badezimmer_proto_rawDescData
}

var file_badezimmer_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_badezimmer_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_badezimmer_proto_goTypes = []any{
	(DeviceKind)(0),                      // 0: badezimmer.DeviceKind
	(DeviceStatus)(0),                    // 1: badezimmer.DeviceStatus
	(DeviceCategory)(0),                  // 2: badezimmer.DeviceCategory
	(TransportProtocol)(0),               // 3: badezimmer.TransportProtocol
	(ErrorCode)(0),                       // 4: badezimmer.ErrorCode
	(MDNSType)(0),                        // 5: badezimmer.MDNSType
	(*ConnectedDevice)(nil),              // 6: badezimmer.ConnectedDevice
	(*ListConnectedDevicesRequest)(nil),  // 7: badezimmer.ListConnectedDevicesRequest
	(*ListConnectedDevicesResponse)(nil), // 8: badezimmer.ListConnectedDevicesResponse
	(*SendActuatorCommandRequest)(nil),   // 9: badezimmer.SendActuatorCommandRequest
	(*ErrorDetails)(nil),                 // 10: badezimmer.ErrorDetails
	(*BadezimmerRequest)(nil),            // 11: badezimmer.BadezimmerRequest
	(*BadezimmerResponse)(nil),           // 12: badezimmer.BadezimmerResponse
	(*SendActuatorCommandResponse)(nil),  // 13: badezimmer.SendActuatorCommandResponse
	(*Color)(nil),                        // 14: badezimmer.Color
	(*LightLampActionRequest)(nil),       // 15: badezimmer.LightLampActionRequest
	(*SinkActionRequest)(nil),            // 16: badezimmer.SinkActionRequest
	(*MDNSQuestion)(nil),                 // 17: badezimmer.MDNSQuestion
	(*MDNSQueryRequest)(nil),             // 18: badezimmer.MDNSQueryRequest
	(*MDNSPointerRecord)(nil),            // 19: badezimmer.MDNSPointerRecord
	(*MDNSSRVRecord)(nil),                // 20: badezimmer.MDNSSRVRecord
	(*MDNSTextRecord)(nil),               // 21: badezimmer.MDNSTextRecord
	(*MDNSARecord)(nil),                  // 22: badezimmer.MDNSARecord
	(*MDNSRecord)(nil),                   // 23: badezimmer.MDNSRecord
	(*MDNSQueryResponse)(nil),            // 24: badezimmer.MDNSQueryResponse
	(*MDNS)(nil),                         // 25: badezimmer.MDNS
	nil,                                  // 26: badezimmer.ConnectedDevice.PropertiesEntry
	nil,                                  // 27: badezimmer.ErrorDetails.MetadataEntry
	nil,                                  // 28: badezimmer.MDNSTextRecord.EntriesEntry
	(*emptypb.Empty)(nil),                // 29: google.protobuf.Empty
	(*timestamppb.Timestamp)(nil),        // 30: google.protobuf.Timestamp
}
var file_badezimmer_proto_depIdxs = []int32{
	0,  // 0: badezimmer.ConnectedDevice.kind:type_name -> badezimmer.DeviceKind
	1,  // 1: badezimmer.ConnectedDevice.status:type_name -> badezimmer.DeviceStatus
	26, // 2: badezimmer.ConnectedDevice.properties:type_name -> badezimmer.ConnectedDevice.PropertiesEntry
	2,  // 3: badezimmer.ConnectedDevice.category:type_name -> badezimmer.DeviceCategory
	3,  // 4: badezimmer.ConnectedDevice.transport_protocol:type_name -> badezimmer.TransportProtocol
	0,  // 5: badezimmer.ListConnectedDevicesRequest.filter_kind:type_name -> badezimmer.DeviceKind
	6,  // 6: badezimmer.ListConnectedDevicesResponse.devices:type_name -> badezimmer.ConnectedDevice
	15, // 7: badezimmer.SendActuatorCommandRequest.light_action:type_name -> badezimmer.LightLampActionRequest
	16, // 8: badezimmer.SendActuatorCommandRequest.sink_action:type_name -> badezimmer.SinkActionRequest
	4,  // 9: badezimmer.ErrorDetails.code:type_name -> badezimmer.ErrorCode
	27, // 10: badezimmer.ErrorDetails.metadata:type_name -> badezimmer.ErrorDetails.MetadataEntry
	29, // 11: badezimmer.BadezimmerRequest.empty:type_name -> google.protobuf.Empty
	7,  // 12: badezimmer.BadezimmerRequest.list_devices:type_name -> badezimmer.ListConnectedDevicesRequest
	9,  // 13: badezimmer.BadezimmerRequest.send_actuator_command:type_name -> badezimmer.SendActuatorCommandRequest
	29, // 14: badezimmer.BadezimmerResponse.empty:type_name -> google.protobuf.Empty
	10, // 15: badezimmer.BadezimmerResponse.error:type_name -> badezimmer.ErrorDetails
	8,  // 16: badezimmer.BadezimmerResponse.list_devices_response:type_name -> badezimmer.ListConnectedDevicesResponse
	13, // 17: badezimmer.BadezimmerResponse.send_actuator_command_response:type_name -> badezimmer.SendActuatorCommandResponse
	14, // 18: badezimmer.LightLampActionRequest.color:type_name -> badezimmer.Color
	5,  // 19: badezimmer.MDNSQuestion.type:type_name -> badezimmer.MDNSType
	17, // 20: badezimmer.MDNSQueryRequest.questions:type_name -> badezimmer.MDNSQuestion
	3,  // 21: badezimmer.MDNSSRVRecord.protocol:type_name -> badezimmer.TransportProtocol
	28, // 22: badezimmer.MDNSTextRecord.entries:type_name -> badezimmer.MDNSTextRecord.EntriesEntry
	19, // 23: badezimmer.MDNSRecord.ptr_record:type_name -> badezimmer.MDNSPointerRecord
	20, // 24: badezimmer.MDNSRecord.srv_record:type_name -> badezimmer.MDNSSRVRecord
	21, // 25: badezimmer.MDNSRecord.txt_record:type_name -> badezimmer.MDNSTextRecord
	22, // 26: badezimmer.MDNSRecord.a_record:type_name -> badezimmer.MDNSARecord
	23, // 27: badezimmer.MDNSQueryResponse.answers:type_name -> badezimmer.MDNSRecord
	23, // 28: badezimmer.MDNSQueryResponse.additional_records:type_name -> badezimmer.MDNSRecord
	30, // 29: badezimmer.MDNS.timestamp:type_name -> google.protobuf.Timestamp
	18, // 30: badezimmer.MDNS.query_request:type_name -> badezimmer.MDNSQueryRequest
	24, // 31: badezimmer.MDNS.query_response:type_name -> badezimmer.MDNSQueryResponse
	7,  // 32: badezimmer.BadezimmerService.ListConnectedDevices:input_type -> badezimmer.ListConnectedDevicesRequest
	9,  // 33: badezimmer.BadezimmerService.SendActuatorCommand:input_type -> badezimmer.SendActuatorCommandRequest
	8,  // 34: badezimmer.BadezimmerService.ListConnectedDevices:output_type -> badezimmer.ListConnectedDevicesResponse
	13, // 35: badezimmer.BadezimmerService.SendActuatorCommand:output_type -> badezimmer.SendActuatorCommandResponse
	34, // [34:36] is the sub-list for method output_type
	32, // [32:34] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_badezimmer_proto_init() }
func file_badezimmer_proto_init() {
	if File_badezimmer_proto != nil {
		return
	}
	file_badezimmer_proto_msgTypes[1].OneofWrappers = []any{}
	file_badezimmer_proto_msgTypes[3].OneofWrappers = []any{
		(*SendActuatorCommandRequest_LightAction)(nil),
		(*SendActuatorCommandRequest_SinkAction)(nil),
	}
	file_badezimmer_proto_msgTypes[5].OneofWrappers = []any{
		(*BadezimmerRequest_Empty)(nil),
		(*BadezimmerRequest_ListDevices)(nil),
		(*BadezimmerRequest_SendActuatorCommand)(nil),
	}
	file_badezimmer_proto_msgTypes[6].OneofWrappers = []any{
		(*BadezimmerResponse_Empty)(nil),
		(*BadezimmerResponse_Error)(nil),
		(*BadezimmerResponse_ListDevicesResponse)(nil),
		(*BadezimmerResponse_SendActuatorCommandResponse)(nil),
	}
	file_badezimmer_proto_msgTypes[7].OneofWrappers = []any{}
	file_badezimmer_proto_msgTypes[9].OneofWrappers = []any{}
	file_badezimmer_proto_msgTypes[10].OneofWrappers = []any{}
	file_badezimmer_proto_msgTypes[17].OneofWrappers = []any{
		(*MDNSRecord_PtrRecord)(nil),
		(*MDNSRecord_SrvRecord)(nil),
		(*MDNSRecord_TxtRecord)(nil),
		(*MDNSRecord_ARecord)(nil),
	}
	file_badezimmer_proto_msgTypes[19].OneofWrappers = []any{
		(*MDNS_QueryRequest)(nil),
		(*MDNS_QueryResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_badezimmer_proto_rawDesc), len(file_badezimmer_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_badezimmer_proto_goTypes,
		DependencyIndexes: file_badezimmer_proto_depIdxs,
		EnumInfos:         file_badezimmer_proto_enumTypes,
		MessageInfos:      file_badezimmer_proto_msgTypes,
	}.Build()
	File_badezimmer_proto = out.File
	file_badezimmer_proto_goTypes = nil
	file_badezimmer_proto_depIdxs = nil
}
