version: "3"

tasks:
  proto:gen:
    desc: Generate code from proto files
    cmds:
      - protoc --python_out=src/badezimmer --pyi_out=src/badezimmer ./proto/*.proto -I ./proto/

  gateway:run:
    desc: Run the API gateway
    cmds:
      - uv run python -m gateway.main