# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import badezimmer_pb2 as badezimmer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in badezimmer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BadezimmerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListConnectedDevices = channel.unary_unary(
                '/badezimmer.BadezimmerService/ListConnectedDevices',
                request_serializer=badezimmer__pb2.ListConnectedDevicesRequest.SerializeToString,
                response_deserializer=badezimmer__pb2.ListConnectedDevicesResponse.FromString,
                _registered_method=True)
        self.SendActuatorCommand = channel.unary_unary(
                '/badezimmer.BadezimmerService/SendActuatorCommand',
                request_serializer=badezimmer__pb2.SendActuatorCommandRequest.SerializeToString,
                response_deserializer=badezimmer__pb2.SendActuatorCommandResponse.FromString,
                _registered_method=True)


class BadezimmerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListConnectedDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendActuatorCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BadezimmerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListConnectedDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConnectedDevices,
                    request_deserializer=badezimmer__pb2.ListConnectedDevicesRequest.FromString,
                    response_serializer=badezimmer__pb2.ListConnectedDevicesResponse.SerializeToString,
            ),
            'SendActuatorCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendActuatorCommand,
                    request_deserializer=badezimmer__pb2.SendActuatorCommandRequest.FromString,
                    response_serializer=badezimmer__pb2.SendActuatorCommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'badezimmer.BadezimmerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('badezimmer.BadezimmerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BadezimmerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListConnectedDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/badezimmer.BadezimmerService/ListConnectedDevices',
            badezimmer__pb2.ListConnectedDevicesRequest.SerializeToString,
            badezimmer__pb2.ListConnectedDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendActuatorCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/badezimmer.BadezimmerService/SendActuatorCommand',
            badezimmer__pb2.SendActuatorCommandRequest.SerializeToString,
            badezimmer__pb2.SendActuatorCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
